ScrollReveal().reveal('.ilustracao', { delay: 500 });
ScrollReveal().reveal('.text', { delay: 700 });
ScrollReveal().reveal('.text-simulacao', { delay: 700 });
ScrollReveal().reveal('.ilustracao2', { delay: 900 });
ScrollReveal().reveal('.vantagens-text', { delay: 700 });
ScrollReveal().reveal('.icons-text', { delay: 700 });
ScrollReveal().reveal('.title-sobrenos', { delay: 700 });
ScrollReveal().reveal('.text-sobrenos', { delay: 700 });
ScrollReveal().reveal('.valores', { delay: 700 });
